[package]
name = "relogio"
version = "0.1.0"
authors = ["Bill Mitchell <wkmitch@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
reqwest = "0.9.20"
serde = "1.0.99"
serde_json = "1.0.40"

[dependencies.pancurses]
pancurses = "0.16"
features = ["wide"]
